testname: Single Packet Loss Audibility Test
testId: SPLAT-Blues_Guitar-40051167010282684
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  id: Explanation
  name: Instructions
  content: '                <h2>Requirements</h2>                <p>For this test
    you will need a pair of Beyerdynamic DT770 PRO headphones, a good audio interface
    (avoid Behringer) and a quiet environment.</p>                <h2>Explanation</h2>                The
    goal of this test is to assess how audible audio glitches are in an audio signal.<br>                You
    will be presented with 12 3-second unlabeled audio tracks in each of the 4 listening
    sessions.<br>                You need to assign each track a score between 0 and
    100 representing how audible the glitch was.<br>                The scale is divided
    into the following five sections: "Not at all", "Barely", "A bit", "Much", and
    "Very Much".                  <h2>Audio Examples</h2>                  Below you
    can find some examples of the audio tracks you will be presented with.<br>                  Listen
    carefully to the examples to understand the scale.<br>                <table>                  <tr>                    <th></th>                    <th>Cello</th>                    <th>Piano</th>                  </tr>                  <tr>                    <td>Not
    at all</td>                    <td>                      <audio controls>                          <source
    src="configs/resources/audio/example_not_at_all_1_stim.wav" type="audio/wav">                          Your
    browser does not support the audio element.                      </audio>                    </td>                    <td>                      <audio
    controls>                          <source src="configs/resources/audio/example_not_at_all_2_ref.wav"
    type="audio/wav">                          Your browser does not support the audio
    element.                      </audio>                    </td>                  </tr>                  <tr>                    <td>A
    bit</td>                    <td>                      <audio controls>                          <source
    src="configs/resources/audio/example_a_bit_1_stim.wav" type="audio/wav">                          Your
    browser does not support the audio element.                      </audio>                    </td>                    <td>                      <audio
    controls>                          <source src="configs/resources/audio/example_a_bit_2_stim.wav"
    type="audio/wav">                          Your browser does not support the audio
    element.                      </audio>                    </td>                  </tr>                  <tr>                    <td>Very
    Much</td>                    <td>                      <audio controls>                          <source
    src="configs/resources/audio/example_very_much_1_stim.wav" type="audio/wav">                          Your
    browser does not support the audio element.                      </audio>                    </td>                    <td>                      <audio
    controls>                          <source src="configs/resources/audio/example_very_much_2_stim.wav"
    type="audio/wav">                          Your browser does not support the audio
    element.                      </audio>                    </td>                  </tr>                </table>                <style>                    table
    {                        margin-left: auto;                        margin-right:
    auto;                        border-collapse: collapse;                    }                    th,
    td {                        border: 0px solid black;                        padding:
    10px;                        text-align: center;                    }                </style>'
- type: generic
  id: Consent
  name: Declaration of consent
  content: <h1>Declaration of consent</h1>      <p>By clicking the 'Next' button,
    you give your consent to the following. Please read the following consent entries
    carefully.</p>      <br/>      <p><i>I confirm that I have read and understand
    the participant information <br/>sheet for the project </i>Towards Perceptual
    Deep Learning-based Packet Loss Concealment.</p>      <br/>      <p><i>I confirm
    that I am 18 years of age or older.</i></p>      <br/>      <p><i>I understand
    that if I have any queries or concerns relating to this <br/>study I can contact
    Luca Vignati (luca.vignati@unitn.it) at any time.</i></p>      <br/>      <p><i>      I
    understand that I have the right to withdraw from this study at any <br/>      time
    without requirement to provide reason, and that if I withdraw,<br/>       any
    data provided up to this point will be retained.</i></p>      <br/>      <p><i>I
    agree for my personal information, including gender, age and listening experience
    to be recorded.</i></p>      <br/>      <p><i>      I understand that the data
    I provide may be presented anonymously in <br/>r      esearch output and publication,
    will be retained securely and indefinitely,<br/>      and may be made accessible
    to future researchers.</i></p>
- type: generic
  id: Volume
  name: Adjust your volume
  content: <h1>Adjust your volume</h1>      <p>Before the experiment begins, please
    adjust your listening volume.</p>      <p>Please do not change the output volume
    of the system from now on.</p>
-
  - random
  - type: splat
    id: 6999-47499-8499-36999-41499-44499-35499-56499-32499-39999
    name: Test in progress
    content: '<p>IMPORTANT: When you press play on a stimulus, let it play till the
      end or hit pause. If you press play on another stimulus before the first finished,
      a glitch will be produced and the test will be invalid.</p>Please rate the audibility
      of the glitch in the following audio examples. How much can you hear it?'
    createAnchor35: false
    createAnchor70: false
    showWaveform: false
    enableLooping: false
    switchBack: true
    randomize: true
    reference: configs/resources/audio/guitar_reference.wav
    stimuli:
      0-6999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/0-6999.wav
      1-47499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/1-47499.wav
      2-8499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/2-8499.wav
      3-36999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/3-36999.wav
      4-41499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/4-41499.wav
      5-44499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/5-44499.wav
      6-35499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/6-35499.wav
      7-56499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/7-56499.wav
      8-32499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/8-32499.wav
      9-39999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/9-39999.wav
      guitar_anchor: configs/resources/audio/guitar_anchor.wav
  - type: splat
    id: 48999-29499-45999-54999-50499-42999-9999-24999-18999-53499
    name: Test in progress
    content: '<p>IMPORTANT: When you press play on a stimulus, let it play till the
      end or hit pause. If you press play on another stimulus before the first finished,
      a glitch will be produced and the test will be invalid.</p>Please rate the audibility
      of the glitch in the following audio examples. How much can you hear it?'
    createAnchor35: false
    createAnchor70: false
    showWaveform: false
    enableLooping: false
    switchBack: true
    randomize: true
    reference: configs/resources/audio/guitar_reference.wav
    stimuli:
      10-48999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/10-48999.wav
      11-29499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/11-29499.wav
      12-45999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/12-45999.wav
      13-54999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/13-54999.wav
      14-50499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/14-50499.wav
      15-42999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/15-42999.wav
      16-9999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/16-9999.wav
      17-24999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/17-24999.wav
      18-18999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/18-18999.wav
      19-53499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/19-53499.wav
      guitar_anchor: configs/resources/audio/guitar_anchor.wav
- type: generic
  id: Pause
  name: Break
  content: <h1>Break</h1>      <p>Please take 5 minutes of rest from this trial. Take
    off your headphones and chill for a while.</p>
-
  - random
  - type: splat
    id: 6999-47499-8499-36999-41499-44499-35499-56499-32499-39999
    name: Test in progress
    content: '<p>IMPORTANT: When you press play on a stimulus, let it play till the
      end or hit pause. If you press play on another stimulus before the first finished,
      a glitch will be produced and the test will be invalid.</p>Please rate the audibility
      of the glitch in the following audio examples. How much can you hear it?'
    createAnchor35: false
    createAnchor70: false
    showWaveform: false
    enableLooping: false
    switchBack: true
    randomize: true
    reference: configs/resources/audio/guitar_reference.wav
    stimuli:
      0-6999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/0-6999.wav
      1-47499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/1-47499.wav
      2-8499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/2-8499.wav
      3-36999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/3-36999.wav
      4-41499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/4-41499.wav
      5-44499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/5-44499.wav
      6-35499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/6-35499.wav
      7-56499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/7-56499.wav
      8-32499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/8-32499.wav
      9-39999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/9-39999.wav
      guitar_anchor: configs/resources/audio/guitar_anchor.wav
  - type: splat
    id: 48999-29499-45999-54999-50499-42999-9999-24999-18999-53499
    name: Test in progress
    content: '<p>IMPORTANT: When you press play on a stimulus, let it play till the
      end or hit pause. If you press play on another stimulus before the first finished,
      a glitch will be produced and the test will be invalid.</p>Please rate the audibility
      of the glitch in the following audio examples. How much can you hear it?'
    createAnchor35: false
    createAnchor70: false
    showWaveform: false
    enableLooping: false
    switchBack: true
    randomize: true
    reference: configs/resources/audio/guitar_reference.wav
    stimuli:
      10-48999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/10-48999.wav
      11-29499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/11-29499.wav
      12-45999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/12-45999.wav
      13-54999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/13-54999.wav
      14-50499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/14-50499.wav
      15-42999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/15-42999.wav
      16-9999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/16-9999.wav
      17-24999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/17-24999.wav
      18-18999: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/18-18999.wav
      19-53499: configs/resources/stimuli/SPLAT-Blues_Guitar-40051167010282684/19-53499.wav
      guitar_anchor: configs/resources/audio/guitar_anchor.wav
- type: finish
  name: Thank you
  content: Thank you for attending
  popupContent: Your results were sent. Goodbye and have a nice day
  showResults: true
  writeResults: true
  questionnaire:
  - type: text
    label: Name
    name: Name
  - type: text
    label: Surname
    name: Surname
  - type: number
    label: Age
    name: Age
    min: 0
    max: 100
    default: 30
  - type: likert
    name: gender
    label: Gender
    response:
    - value: male
      label: Male
    - value: female
      label: Female
  - type: likert
    name: Musical Proficiency
    label: Musical Proficiency
    response:
    - value: beginner
      label: Beginner
    - value: intermediate
      label: Intermediate
    - value: advanced
      label: Advanced
  - type: text
    label: Email
    name: email